---
- name: Create shared resources directory
  ansible.builtin.file:
    path: "{{ nifi_registry_config_dirs.external_config }}"
    state: directory
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    mode: "0750"

- name: Update nifi-registry.properties
  ansible.builtin.lineinfile:
    path: "{{ nifi_registry_config_dirs.home }}/conf/nifi-registry.properties"
    line: "{{ item.key }}={{ item.value }}"
    regexp: ^{{ item.key }}
  with_dict: "{{ nifi_registry_properties }}"

- name: Update bootstrap.conf
  ansible.builtin.lineinfile:
    path: "{{ nifi_registry_config_dirs.home }}/conf/bootstrap.conf"
    line: "{{ item.key }}={{ item.value }}"
    regexp: ^{{ item.key }}
  with_dict: "{{ bootstrap }}"

- name: Update logback.xml
  xml:
    path: "{{ nifi_registry_config_dirs.home }}/conf/logback.xml"
    xpath: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ logback }}"

- name: Update identity-providers.xml
  when: identity_providers['/identityProviders/provider/identifier'] | length
  block:
    - name: Uncomment block in identity-providers.xml
      ansible.builtin.replace:
        path: "{{ nifi_registry_config_dirs.home }}/conf/identity-providers.xml"
        regexp: ^.*To enable the {{ identity_providers['/identityProviders/provider/identifier'] }}.*$
        replace: ""
    - name: Update properties in identity-providers.xml
      xml:
        path: "{{ nifi_registry_config_dirs.home }}/conf/identity-providers.xml"
        xpath: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ identity_providers }}"

- name: Update authorizers.xml
  when: authorizers['/authorizers/userGroupProvider/identifier'] | length
  block:
    - name: Uncomment block in authorizers.xml
      ansible.builtin.replace:
        path: "{{ nifi_registry_config_dirs.home }}/conf/authorizers.xml"
        regexp: ^.*To enable the {{ authorizers['/authorizers/userGroupProvider/identifier'] }}.*$
        replace: ""
    - name: Update properties in authorizers.xml
      xml:
        path: "{{ nifi_registry_config_dirs.home }}/conf/authorizers.xml"
        xpath: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ authorizers }}"

- name: Update providers.xml
  xml:
    path: "{{ nifi_registry_config_dirs.home }}/conf/providers.xml"
    xpath: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ providers }}"
