---
- name: Prepare system
  ansible.builtin.import_task: prepare.yml
- name: Install NiFi Registry
  ansible.builtin.import_task: install.yml
- name: Customize NiFi Registry
  ansible.builtin.import_task: customize.yml
- name: Run NiFi Registry as system service
  ansible.builtin.import_task: run.yml
